# サイト情報
site_name: TechCommitドキュメント
site_description: TechCommitを活用するためのドキュメントサイト
site_author: TechTraining

# リポジトリ
repo_url: https://github.com/tech-training/tech-commit-doc
repo_name: tech-training/tech-commit-tutorial
edit_uri: edit/develop/docs/

# コピーライト
copyright: '&copy; 2020 株式会社テクトレ'

# デザイン設定
theme:
  name: material
  language: ja
  favicon: images/favicon.ico
  palette:
    primary: indigo
    accent: amber

# ページ構成
nav:
- ホーム: index.md
- 利用準備:
  - Slackアプリのインストールとワークスペースへの参加: join-slack.md
  - Zoomのインストールと基本操作: install-zoom.md
  - TechCommit Webサイトの設定: preparation-site.md
- 活用ステップ:
  - 入門: beginner.md
  - 基礎学習: learn-base.md
  - 実践: practice.md
- 活用方法:
  - Slack:
    - Slackチャンネルの参加方法: join-slack-channel.md
  - TechCommit Webサイト:
    - 学習日報: learning-report.md
    - 学習日報ツイート機能: learning-report-tweet.md
    - QA広場: qa-board.md
    - 挑戦状: challenge.md
    - ブックマーク: bookmark.md
  - イベント:
    - オンラインもくもく会: mokumoku.md
    - オンライン週末勉強会: online-event.md
