# Googleアナリティクス
google_analytics:
  - UA-135645540-4
  - auto

# サイト情報
site_name: TechCommitドキュメント
site_description: TechCommitを活用するためのドキュメントサイト
site_author: TechTraining

# リポジトリ
repo_url: https://github.com/tech-training/tech-commit-doc
repo_name: tech-training/tech-commit-tutorial
edit_uri: edit/develop/docs/

# コピーライト
copyright: '&copy; 2020 株式会社テクトレ'

# デザイン設定
theme:
  name: material
  language: ja
  favicon: images/favicon.ico
  palette:
    primary: preference
    accent: amber
  logo: images/header/techcommit_logo.png

extra_css:
  - css/common/container.css
  - css/common/header.css
  - css/common/sidebar.css

# ページ構成
nav:
- ホーム: index.md
- チュートリアル:
  - ようこそTechCommitへ: tutorial/about.md
  - Step1. 利用環境を整えよう！: tutorial/preparation.md
  - Step2. メンバーと仲良くなろう！: tutorial/get-along-with-each-other.md
  - Step3. 興味のある話題に参加しよう！: tutorial/join-slack-channel.md
  - Step4. 様々なイベントに参加しよう！: tutorial/join-event.md
  - Step5. 学習にもっとCommitしよう！: tutorial/include-techcommit-in-your-life.md
- 目標別活用例:
  - 個人アプリ開発: develop-app.md
- 活用方法:
  - TechCommit Webサイト:
    - 学習日報: learning-report.md
    - 学習日報ツイート設定: learning-report-tweet.md
    - QA広場: qa-board.md
    - 挑戦状: challenge.md
    - ブックマーク: bookmark.md
  - イベント:
    - オンラインもくもく会: mokumoku.md
    - オンライン週末勉強会: online-event.md
    - 講師募集: looking-for-organizer.md
- サイト修正等の提案・報告: contribute.md
