# サイト情報
site_name: TechCommitドキュメント
site_description: TechCommitを活用するためのドキュメントサイト
site_author: TechTraining

# リポジトリ
repo_url: https://github.com/tech-training/tech-commit-doc
repo_name: tech-training/tech-commit-tutorial
edit_uri: edit/develop/docs/

# コピーライト
copyright: '&copy; 2020 株式会社テクトレ'

# デザイン設定
theme:
  name: material
  language: ja
  favicon: images/favicon.ico
  palette:
    primary: preference
    accent: amber
  logo: images/header/techcommit_logo.png

extra_css:
  - css/common/container.css
  - css/common/header.css
  - css/common/sidebar.css

# ページ構成
nav:
- ホーム: index.md
- チュートリアル:
  - このチュートリアルの意義: tutorial/tutorial-significance.md
  - TechCommitが大事にしていること: tutorial/techcommit-concept.md
  - 利用準備をしよう:
    - Slackアプリのインストール方法: tutorial/install-slack.md
    - Zoomのインストール方法: tutorial/install-zoom.md
    - Zoomの基本操作: tutorial/zoom-basic.md
    - TechCommitのワークスペースへ参加する方法: tutorial/join-slack.md
    - TechCommit Webサイトの設定: tutorial/preparation-site.md
  - お互いに仲良くなるためにまずやるべきこと: tutorial/get-along-with-each-other.md
  - 興味のあるチャンネルへ参加して仲間を作ろう: tutorial/join-slack-channel.md
  - イベントに参加しよう: tutorial/join-event.md
- 目標別活用例:
  - 個人アプリ開発: develop-app.md
- 活用方法:
  - TechCommit Webサイト:
    - 学習日報: learning-report.md
    - 学習日報ツイート設定: learning-report-tweet.md
    - QA広場: qa-board.md
    - 挑戦状: challenge.md
    - ブックマーク: bookmark.md
  - イベント:
    - オンラインもくもく会: mokumoku.md
    - オンライン週末勉強会: online-event.md
    - 講師募集: looking-for-organizer.md
