# サイト情報
site_name: TechCommitドキュメント
site_description: TechCommitを活用するためのドキュメントサイト
site_author: TechTraining

# リポジトリ
repo_url: https://github.com/tech-training/tech-commit-doc
repo_name: tech-training/tech-commit-tutorial
edit_uri: edit/develop/docs/

# コピーライト
copyright: '&copy; 2020 株式会社テクトレ'

# デザイン設定
theme:
  name: material
  language: ja
  favicon: images/favicon.ico
  palette:
    primary: preference
    accent: amber
  logo: images/header/techcommit_logo.png

extra_css:
  - css/common/container.css
  - css/common/header.css
  - css/common/sidebar.css

# ページ構成
nav:
- ホーム: index.md
- 利用準備:
  - Slackアプリのインストールとワークスペースへの参加: join-slack.md
  - Slackチャンネルの参加方法: join-slack-channel.md
  - Zoomのインストールと基本操作: install-zoom.md
  - TechCommit Webサイトの設定: preparation-site.md
- チュートリアル:
  - TechCommitへようこそ！: tutorial/welcome-to-techcommit.md
  - TechCommitが大事にしていること、思想: tutorial/important-concepts.md
  - TechCommitの活動: tutorial/techcommit-activities.md
  - 自己紹介／既存参加者: tutorial/know-each-other.md
  - 興味のあるチャンネルに参加しよう: tutorial/join-interest-channel.md
  - もくもく会やイベントに参加して交流／勉強しよう: tutorial/join-event.md
  - 機能やサービスを活用しよう: tutorial/use-features-and-services.md
  - 習慣化する準備をしよう: tutorial/make-learning-plan.md
  - お互いに成果や成長を共有し合おう: tutorial/share-output.md
  - わからないことを質問してみよう: tutorial/ask-questions.md
- 目標別活用例:
  - 個人アプリ開発: develop-app.md
- 活用方法:
  - TechCommit Webサイト:
    - 学習日報: learning-report.md
    - 学習日報ツイート設定: learning-report-tweet.md
    - QA広場: qa-board.md
    - 挑戦状: challenge.md
    - ブックマーク: bookmark.md
  - イベント:
    - オンラインもくもく会: mokumoku.md
    - オンライン週末勉強会: online-event.md
    - 講師募集: looking-for-organizer.md
